name: ipd-ref-generator
channels:
  - conda-forge
  - bioconda
  - main
  - anaconda
  - r
dependencies:
  - nextflow=22.04.0
  - go
  - R
  - r-tidyverse
  - bbmap=38.96
  - ncbi-datasets-cli
  - vsearch=2.17.0
  - unzip
  - zstd
  - biopython=1.79
  - pysam=0.19.1
  - pip=22.1.2
  - pip:
    - graphviz==0.20
    - requests==2.28.1
    - pysam==0.19.1
